import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const poppins = Poppins({
	weight: ["400", "500", "600", "700", "800"],
	variable: "--font-poppins",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "RAIPETSHOP - UTS PBW",
	description: "Created by Rai Wirawan, Generated by Next.js",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${poppins.variable} ${poppins.className} antialiased`}>
				{children}
			</body>
		</html>
	);
}
